import { createClient } from '@supabase/supabase-js';

const supabase = import.meta.env.VITE_SUPABASE_URL && import.meta.env.VITE_SUPABASE_ANON_KEY
  ? createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_ANON_KEY)
  : null;
const demoImage = 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=900&q=85';
const localPhotos = [
  'WhatsApp Image 2026-09-03 at 16.35.24 (1).jpeg', 'WhatsApp Image 2026-09-03 at 16.35.24.jpeg',
  'WhatsApp Image 2026-09-03 at 16.35.25 (1).jpeg', 'WhatsApp Image 2026-09-03 at 16.35.25 (2).jpeg',
  'WhatsApp Image 2026-09-03 at 16.35.25.jpeg', 'WhatsApp Image 2026-09-03 at 16.35.26 (1).jpeg',
  'WhatsApp Image 2026-09-03 at 16.35.26.jpeg', 'WhatsApp Image 2026-09-03 at 16.35.27 (1).jpeg',
  'WhatsApp Image 2026-09-03 at 16.35.27 (2).jpeg', 'WhatsApp Image 2026-09-03 at 16.35.27.jpeg',
  'WhatsApp Image 2026-09-03 at 16.35.28 (1).jpeg', 'WhatsApp Image 2026-09-03 at 16.35.28 (2).jpeg',
  'WhatsApp Image 2026-09-03 at 16.35.28.jpeg', 'WhatsApp Image 2026-09-03 at 16.35.29.jpeg'
].map(encodeURI);
const sampleVehicle = { id: 'sample-onix', name: 'Onix RS Hatch Black 1.0 Turbo', year: '2023/2024', color: 'Preto', engine: '1.0 Turbo', km: '34.500 km', fuel: 'Flex', price: 89900, items: 'Ar Condicionado, Alarme, Trava Elétrica, Vidro Elétrico, Bancos em Couro, Freio ABS, Espelhos Elétricos, Conta-Giro, Película Protetora, Turbo, Retrovisor Elétrico, Computador de Bordo, Porta Malas Elétrico, Desembaçador Traseiro, Controle de Tração, Rodas de Liga Leve, Controle de Som no Volante, Direção Elétrica, Air Bag, Sensor de Estacionamento Traseiro, Volante Escamoteável, Câmera de Ré, Botão Start/Stop, Bluetooth, USB, Controle de Estabilidade, Câmbio Automático', image: localPhotos[4], photos: localPhotos };
const $ = (selector) => document.querySelector(selector);
const galleryStyle = document.createElement('style'); galleryStyle.textContent = '.vehicle-thumbs{display:flex;gap:5px;padding:8px 12px 0;overflow-x:auto}.vehicle-thumb{flex:0 0 42px;height:32px;border:2px solid transparent;border-radius:4px;background:center/cover no-repeat;opacity:.65;cursor:pointer}.vehicle-thumb.selected{border-color:#d3e83c;opacity:1}.photo-count{position:absolute;right:13px;top:13px;background:#fff;padding:7px 9px;border-radius:5px;font-size:10px;color:#1c594b;font-weight:700}'; document.head.appendChild(galleryStyle);
galleryStyle.textContent += '.public-vehicle{min-height:100vh;padding:30px 6vw 70px;background:#f7f9f7}.public-header{display:flex;align-items:center;justify-content:space-between;max-width:1180px;margin:0 auto 32px}.public-brand{color:#1c594b;font:800 20px Manrope;letter-spacing:1px}.public-layout{max-width:1180px;margin:auto;display:grid;grid-template-columns:1.2fr .8fr;gap:45px}.public-gallery{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.public-gallery img{width:100%;height:250px;object-fit:cover;border-radius:8px}.public-gallery img:first-child{grid-column:span 2;height:430px}.public-info h1{font:800 clamp(30px,4vw,52px)/1.05 Manrope;margin:12px 0}.public-muted{color:#71807b}.public-price{font:800 29px Manrope;margin:30px 0 20px}.public-specs{display:grid;grid-template-columns:1fr 1fr;border-top:1px solid #e5ebe8;border-bottom:1px solid #e5ebe8;padding:18px 0;gap:18px}.public-specs span{display:block;color:#71807b;font-size:11px;text-transform:uppercase}.public-specs strong{display:block;margin-top:4px}.public-items{color:#53645e;font-size:13px;line-height:1.7;margin:22px 0}.public-contact{width:100%}@media(max-width:800px){.public-layout{display:block}.public-gallery img,.public-gallery img:first-child{height:210px}.public-gallery img:first-child{height:280px}.public-info{padding-top:28px}}';
galleryStyle.textContent += '.vehicle-image{cursor:zoom-in}.public-gallery img{cursor:zoom-in}.image-viewer{position:fixed;inset:0;z-index:20;background:#071512ed;display:flex;align-items:center;justify-content:center;padding:60px 90px}.image-viewer.hidden{display:none}.image-viewer img{max-width:90vw;max-height:82vh;object-fit:contain;border-radius:6px}.viewer-close,.viewer-arrow{position:absolute;color:#fff;background:#ffffff22;border:1px solid #ffffff44;border-radius:50%;display:grid;place-items:center}.viewer-close{top:20px;right:25px;width:42px;height:42px;font-size:28px}.viewer-arrow{top:50%;transform:translateY(-50%);width:52px;height:52px;font-size:45px;line-height:1}.viewer-previous{left:25px}.viewer-next{right:25px}.viewer-counter{position:absolute;bottom:22px;color:#fff;font-size:13px}@media(max-width:600px){.image-viewer{padding:50px 48px}.viewer-arrow{width:42px;height:42px;font-size:35px}.viewer-previous{left:8px}.viewer-next{right:8px}}';
let vehicles = JSON.parse(localStorage.getItem('noahVehicles') || 'null') || [sampleVehicle];
let shares = Number(localStorage.getItem('noahShares') || 0);
let selectedImage = '';
let editingId = null;
let selectedImages = [];
const savedSample = vehicles.find(vehicle => vehicle.id === 'sample-onix');
if (savedSample && (!savedSample.photos || savedSample.image === demoImage)) { savedSample.photos = localPhotos; savedSample.image = localPhotos[4]; saveVehicles(); }

function money(value) { return Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }); }
function saveVehicles() { localStorage.setItem('noahVehicles', JSON.stringify(vehicles)); }
async function loadVehicles() {
  if (!supabase) return;
  const { data, error } = await supabase.from('vehicles').select('*').order('created_at', { ascending: false });
  if (error || !data?.length) return;
  vehicles = data.map(vehicle => ({
    id: vehicle.id,
    name: vehicle.title,
    year: String(vehicle.year || ''),
    color: vehicle.color || '',
    engine: vehicle.engine || '',
    km: vehicle.mileage ? `${vehicle.mileage.toLocaleString('pt-BR')} km` : '',
    fuel: vehicle.fuel || 'Flex',
    price: vehicle.price || 0,
    items: vehicle.items || vehicle.description || '',
    image: vehicle.image_url || demoImage,
    photos: vehicle.image_url ? [vehicle.image_url] : []
  }));
}
function render() {
  const query = $('#searchInput').value.toLowerCase().trim();
  const visible = vehicles.filter(vehicle => `${vehicle.name} ${vehicle.year} ${vehicle.color}`.toLowerCase().includes(query));
  $('#vehicleCount').textContent = vehicles.length;
  $('#stockValue').textContent = money(vehicles.reduce((total, vehicle) => total + Number(vehicle.price || 0), 0));
  $('#shareCount').textContent = shares;
  $('#vehicleGrid').innerHTML = visible.map(vehicle => { const photos = vehicle.photos || [vehicle.image || demoImage]; const thumbnails = photos.map((photo, index) => `<button class="vehicle-thumb ${index === 0 ? 'selected' : ''}" data-photo="${photo}" data-vehicle="${vehicle.id}" style="background-image:url('${photo}')" aria-label="Ver foto ${index + 1}"></button>`).join(''); return `<article class="vehicle-card"><div class="vehicle-image" data-main-image="${vehicle.id}" style="background-image:url('${photos[0]}')"><span class="vehicle-tag">DISPONÍVEL</span><span class="photo-count">${photos.length} fotos</span></div><div class="vehicle-thumbs">${thumbnails}</div><div class="vehicle-body"><h4>${escapeHtml(vehicle.name)}</h4><p>${escapeHtml(vehicle.year)} · ${escapeHtml(vehicle.color)}</p><div class="vehicle-details"><span>${escapeHtml(vehicle.km || 'Km não informado')}</span><span>•</span><span>${escapeHtml(vehicle.fuel || 'Flex')}</span><span>•</span><span>${escapeHtml(vehicle.engine || 'Motor')}</span></div><div class="vehicle-price">${money(vehicle.price)}</div><div class="card-actions"><button class="whatsapp-button" data-id="${vehicle.id}">Enviar no WhatsApp ↗</button><button class="delete-button" title="Excluir veículo" data-delete="${vehicle.id}">×</button></div></div></article>`; }).join('');
  $('#emptyState').classList.toggle('hidden', visible.length !== 0);
  $('#vehicleGrid').classList.toggle('hidden', visible.length === 0);
  document.querySelectorAll('.vehicle-card').forEach(card => { const vehicleId = card.querySelector('[data-id]')?.dataset.id; const editButton = document.createElement('button'); editButton.className = 'secondary-button edit-button'; editButton.dataset.edit = vehicleId; editButton.textContent = 'Editar'; const linkButton = document.createElement('button'); linkButton.className = 'secondary-button link-button'; linkButton.dataset.link = vehicleId; linkButton.textContent = 'Copiar link'; card.querySelector('.card-actions').prepend(linkButton, editButton); });
}
function escapeHtml(value) { return String(value || '').replace(/[&<>'"]/g, character => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[character])); }
function publicUrl(vehicle) { return `${location.href.split('#')[0]}#carro=${encodeURIComponent(vehicle.id)}`; }
let viewerPhotos = [];
let viewerIndex = 0;
function openImageViewer(photos, index = 0) { viewerPhotos = photos; viewerIndex = index; $('#imageViewer').classList.remove('hidden'); updateImageViewer(); }
function updateImageViewer() { $('#viewerImage').src = viewerPhotos[viewerIndex]; $('#viewerCounter').textContent = `${viewerIndex + 1} / ${viewerPhotos.length}`; }
function closeImageViewer() { $('#imageViewer').classList.add('hidden'); }
function moveImageViewer(direction) { if (!viewerPhotos.length) return; viewerIndex = (viewerIndex + direction + viewerPhotos.length) % viewerPhotos.length; updateImageViewer(); }
function showPublicVehicle(vehicle) { if (!vehicle) return; $('#loginScreen').classList.add('hidden'); $('#app').classList.add('hidden'); const publicArea = $('#publicVehicle'); publicArea.classList.remove('hidden'); const photos = vehicle.photos || [vehicle.image || demoImage]; publicArea.innerHTML = `<header class="public-header"><div class="public-brand">NOAH <span>VEÍCULOS</span></div><span class="public-muted">Catálogo de veículos</span></header><section class="public-layout"><div class="public-gallery">${photos.map(photo => `<img src="${photo}" alt="${escapeHtml(vehicle.name)}">`).join('')}</div><article class="public-info"><span class="public-muted">NOAH VEÍCULOS · DISPONÍVEL</span><h1>${escapeHtml(vehicle.name)}</h1><p class="public-muted">${escapeHtml(vehicle.year)} · ${escapeHtml(vehicle.color)}</p><div class="public-price">${money(vehicle.price)}</div><div class="public-specs"><div><span>Quilometragem</span><strong>${escapeHtml(vehicle.km || 'Não informado')}</strong></div><div><span>Combustível</span><strong>${escapeHtml(vehicle.fuel || 'Flex')}</strong></div><div><span>Motor</span><strong>${escapeHtml(vehicle.engine || 'Não informado')}</strong></div><div><span>Fotos</span><strong>${photos.length} imagens</strong></div></div><p class="public-items"><strong>Itens:</strong><br>${escapeHtml(vehicle.items || 'Consulte a loja.')}</p><a class="primary-button public-contact" href="https://wa.me/?text=${encodeURIComponent(`Olá! Tenho interesse no ${vehicle.name}: ${publicUrl(vehicle)}`)}" target="_blank">Tenho interesse neste veículo ↗</a></article></section>`; }
function openModal(vehicle = null) { editingId = vehicle?.id || null; selectedImages = vehicle?.photos || (vehicle?.image ? [vehicle.image] : []); $('#vehicleModal').classList.remove('hidden'); $('.modal-card h2').textContent = editingId ? 'Editar veículo' : 'Adicionar veículo'; $('.modal-card .mini-label').textContent = editingId ? 'EDITAR ANÚNCIO' : 'NOVO ANÚNCIO'; if (vehicle) { $('#vehicleName').value = vehicle.name; $('#vehicleYear').value = vehicle.year; $('#vehicleColor').value = vehicle.color; $('#vehicleEngine').value = vehicle.engine || ''; $('#vehicleKm').value = vehicle.km || ''; $('#vehicleFuel').value = vehicle.fuel || 'Flex'; $('#vehiclePrice').value = vehicle.price; $('#vehicleItems').value = vehicle.items || ''; selectedImage = vehicle.image || ''; $('#imagePreview').style.backgroundImage = `url('${selectedImage}')`; $('#imagePreview').querySelector('div').classList.add('hidden'); } $('#vehicleName').focus(); }
function closeModal() { editingId = null; selectedImages = []; $('#vehicleModal').classList.add('hidden'); $('#vehicleForm').reset(); selectedImage = ''; $('#imagePreview').style.backgroundImage = ''; $('#imagePreview').querySelector('div').classList.remove('hidden'); $('.modal-card h2').textContent = 'Adicionar veículo'; $('.modal-card .mini-label').textContent = 'NOVO ANÚNCIO'; }
async function shareVehicle(vehicle) { const text = `Olá! Tenho interesse neste veículo da Noah Veículos:\n\n*${vehicle.name}*\nAno: ${vehicle.year}\nCor: ${vehicle.color}\nMotor: ${vehicle.engine}\nKm: ${vehicle.km}\nCombustível: ${vehicle.fuel}\n\nItens: ${vehicle.items}\n\n*Valor: ${money(vehicle.price)}*`; shares++; localStorage.setItem('noahShares', shares); render(); const photos = vehicle.photos || (vehicle.image ? [vehicle.image] : []); let files = []; try { files = await Promise.all(photos.map(async (photo, index) => { const response = await fetch(photo); if (!response.ok) throw new Error('Não foi possível carregar a foto.'); const blob = await response.blob(); return new File([blob], `${vehicle.name}-${index + 1}.jpg`, { type: blob.type || 'image/jpeg' }); })); } catch (error) { files = []; } if (files.length && navigator.share && navigator.canShare && navigator.canShare({ files })) { try { await navigator.share({ text, files }); return; } catch (error) { if (error.name === 'AbortError') return; } } files.forEach(file => { const download = document.createElement('a'); download.href = URL.createObjectURL(file); download.download = file.name; download.click(); URL.revokeObjectURL(download.href); }); window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank'); if (files.length) alert(`As ${files.length} fotos foram baixadas. No WhatsApp, clique no clipe, selecione todas elas e envie junto com a mensagem.`); }

$('#loginForm').addEventListener('submit', async event => { event.preventDefault(); $('#loginError').textContent = ''; if (!supabase) { $('#loginError').textContent = 'Configuração do Supabase ausente.'; return; } const { error } = await supabase.auth.signInWithPassword({ email: $('#username').value.trim(), password: $('#password').value }); if (error) { $('#loginError').textContent = 'E-mail ou senha incorretos.'; return; } sessionStorage.setItem('noahLoggedIn', 'true'); await loadVehicles(); $('#loginScreen').classList.add('hidden'); $('#app').classList.remove('hidden'); render(); });
$('#logoutButton').addEventListener('click', async () => { await supabase?.auth.signOut(); sessionStorage.removeItem('noahLoggedIn'); location.reload(); });
$('#openModalButton').addEventListener('click', openModal); $('#emptyAddButton').addEventListener('click', openModal); $('#closeModalButton').addEventListener('click', closeModal); $('#cancelModalButton').addEventListener('click', closeModal); $('#searchInput').addEventListener('input', render);
$('#imagePreview').addEventListener('click', () => $('#vehicleImage').click());
$('#vehicleImage').setAttribute('multiple', 'multiple');
$('.photo-field>span').textContent = 'Fotos do veículo';
$('#vehicleImage').addEventListener('change', event => { const files = Array.from(event.target.files); if (!files.length) return; Promise.all(files.map(file => new Promise(resolve => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.readAsDataURL(file); }))).then(images => { selectedImages = images; selectedImage = images[0]; $('#imagePreview').style.backgroundImage = `url('${selectedImage}')`; $('#imagePreview').querySelector('div').classList.add('hidden'); }); });
$('#vehicleForm').addEventListener('submit', event => { event.preventDefault(); const existing = vehicles.find(vehicle => vehicle.id === editingId); const photos = selectedImages.length ? selectedImages : (existing?.photos || []); const updated = { id: editingId || Date.now().toString(), name: $('#vehicleName').value, year: $('#vehicleYear').value, color: $('#vehicleColor').value, engine: $('#vehicleEngine').value, km: $('#vehicleKm').value, fuel: $('#vehicleFuel').value, price: Number($('#vehiclePrice').value.replace(/\D/g, '')), items: $('#vehicleItems').value, image: selectedImage || existing?.image || demoImage, photos }; if (editingId) { vehicles = vehicles.map(vehicle => vehicle.id === editingId ? updated : vehicle); } else { vehicles.unshift(updated); } saveVehicles(); closeModal(); render(); });
$('#vehicleGrid').addEventListener('click', event => { const shareId = event.target.dataset.id; const deleteId = event.target.dataset.delete; const editId = event.target.dataset.edit; const linkId = event.target.dataset.link; const photo = event.target.dataset.photo; const imageArea = event.target.closest('.vehicle-image'); if (imageArea) { const vehicle = vehicles.find(item => item.id === imageArea.dataset.mainImage); openImageViewer(vehicle.photos || [vehicle.image || demoImage]); return; } if (photo) { const mainImage = document.querySelector(`[data-main-image="${event.target.dataset.vehicle}"]`); mainImage.style.backgroundImage = `url('${photo}')`; event.target.closest('.vehicle-thumbs').querySelectorAll('.vehicle-thumb').forEach(button => button.classList.remove('selected')); event.target.classList.add('selected'); } if (linkId) { const link = publicUrl(vehicles.find(vehicle => vehicle.id === linkId)); navigator.clipboard?.writeText(link); alert('Link copiado. Agora você pode enviar para o cliente.'); } if (editId) openModal(vehicles.find(vehicle => vehicle.id === editId)); if (shareId) shareVehicle(vehicles.find(vehicle => vehicle.id === shareId)); if (deleteId && confirm('Excluir este veículo do catálogo?')) { vehicles = vehicles.filter(vehicle => vehicle.id !== deleteId); saveVehicles(); render(); } });
$('#viewerClose').addEventListener('click', closeImageViewer); $('#viewerPrevious').addEventListener('click', () => moveImageViewer(-1)); $('#viewerNext').addEventListener('click', () => moveImageViewer(1)); $('#imageViewer').addEventListener('click', event => { if (event.target.id === 'imageViewer') closeImageViewer(); }); document.addEventListener('keydown', event => { if ($('#imageViewer').classList.contains('hidden')) return; if (event.key === 'ArrowLeft') moveImageViewer(-1); if (event.key === 'ArrowRight') moveImageViewer(1); if (event.key === 'Escape') closeImageViewer(); });
$('#publicVehicle').addEventListener('click', event => { if (event.target.tagName !== 'IMG') return; const publicId = new URLSearchParams(location.hash.replace('#', '?')).get('carro'); const vehicle = vehicles.find(item => item.id === publicId); openImageViewer(vehicle?.photos || [event.target.src]); });
const publicId = new URLSearchParams(location.hash.replace('#', '?')).get('carro');
if (publicId) showPublicVehicle(vehicles.find(vehicle => vehicle.id === publicId)); else if (supabase) { supabase.auth.getSession().then(async ({ data }) => { if (!data.session) return; await loadVehicles(); $('#loginScreen').classList.add('hidden'); $('#app').classList.remove('hidden'); render(); }); }
